export const blogs = [
  {
    author: "dev.to staff",
    team: "The DEV Team",
    date: "Mar 25",
    title: "Top 7 Featured DEV Posts of the Week",
    hashtag: "#top7",
    reactions: 22,
    comments: 7,
    read_time: "2 min read",
  },
  {
    author: "JohnDoe",
    team: "Tech Insights",
    date: "Mar 20",
    title: "10 JavaScript Tricks You Didn’t Know",
    hashtag: "#javascript",
    reactions: 45,
    comments: 12,
    read_time: "5 min read",
  },
  {
    author: "JaneDev",
    team: "Code Masters",
    date: "Mar 22",
    title: "How to Ace Your Next Coding Interview",
    hashtag: "#career",
    reactions: 30,
    comments: 9,
    read_time: "4 min read",
  },
  {
    author: "AIWizard",
    team: "ML Enthusiasts",
    date: "Mar 23",
    title: "Understanding LLMs: A Beginner’s Guide",
    hashtag: "#ai",
    reactions: 50,
    comments: 15,
    read_time: "6 min read",
  },
  {
    author: "ReactGuru",
    team: "Frontend Masters",
    date: "Mar 19",
    title: "React Performance Optimization Tips",
    hashtag: "#react",
    reactions: 38,
    comments: 8,
    read_time: "3 min read",
  },
  {
    author: "Pythonista",
    team: "Data Science Hub",
    date: "Mar 18",
    title: "Top 5 Pandas Functions Every Data Scientist Should Know",
    hashtag: "#python",
    reactions: 60,
    comments: 20,
    read_time: "5 min read",
  },
  {
    author: "CyberSecGeek",
    team: "Security Watch",
    date: "Mar 21",
    title: "Cybersecurity Best Practices for Developers",
    hashtag: "#security",
    reactions: 27,
    comments: 6,
    read_time: "4 min read",
  },
  {
    author: "CSSWizard",
    team: "Frontend Gurus",
    date: "Mar 17",
    title: "Mastering CSS Grid in 2025",
    hashtag: "#css",
    reactions: 35,
    comments: 10,
    read_time: "3 min read",
  },
  {
    author: "CloudNinja",
    team: "DevOps Squad",
    date: "Mar 16",
    title: "Deploying a Full-Stack App with Docker & Kubernetes",
    hashtag: "#devops",
    reactions: 42,
    comments: 14,
    read_time: "6 min read",
  },
  {
    author: "Rustacean",
    team: "System Programming",
    date: "Mar 15",
    title: "Why Rust is the Future of System Programming",
    hashtag: "#rust",
    reactions: 25,
    comments: 5,
    read_time: "4 min read",
  },
];
